version: '3'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app  # Монтируем весь проект
      - static_volume:/app/static
      - media_volume:/app/media
      - sqlite_data:/app/data
    env_file:
      - .env
    expose:
      - 8000
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn auction.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  sqlite_data: